schema-version: 1.0
name: ubuntu

system:
  user: ubuntu
  container: "{% piper.name %}:{% piper.version %}"

providers:
  virtualbox:
    ova: https://s3.eu-west-3.amazonaws.com/xbee.repository/{% piper.name %}/{% piper.name %}-{% piper.version %}-amd64.ova
  aws:
    eu-west-3: ami-006987b5e26f0d62e
    af-south-1: ami-05374610024e957a7
    ap-east-1: ami-67efac16
    ap-northeast-1: ami-014feb7ea40a68cac
    ap-south-1: ami-01ed496a0cb4b0cb8
    ap-southeast-1: ami-02842ae8870f3bf28
    ca-central-1: ami-0fd4c28ed3f6eb08a
    eu-central-1: ami-0f2d19ebd832faeee
    eu-north-1: ami-0bc7ccdb4fa02d8ec
    eu-south-1: ami-0f02226ccdbd1afc6
    eu-west-1: ami-00e1a1c196475d9e1
    me-south-1 : ami-0c293a4b859663e00
    sa-east-1: ami-0824797eca8add239
    us-east-1: ami-0d324124b7b7eec66
    us-west-1: ami-06be7b637b6be3976
    cn-north-1 : ami-08aa4956dd72a5dd8
    cn-northwest-1: ami-0bcc3e55aa0d2edd6
    ap-northeast-2: ami-0e11152ae494b2405
    ap-southeast-2 : ami-0d267520de813dd12
    eu-west-2: ami-051b8d7d82d7ba3f5
    us-east-2: ami-00ea3ade739217b29
    us-west-2: ami-0545062d0daec9308
    ap-northeast-3: ami-008b573ca8bd84d19
    eu-west-3: ami-0407538359da694a6

var:
  timezone: Europe/Paris
 
provision:
  - shell: msg.sh
  - shell: rm -f /etc/localtime && ln -sf /usr/share/zoneinfo/{% timezone %} /etc/localtime

up:
  - shell: hostnamectl set-hostname {{ .host.name }}
